#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Resolve images/linux/requirements.in into a fully-pinned images/linux/requirements.txt.
#
#   scripts/compile-python-deps.sh           # regenerate the lock
#   scripts/compile-python-deps.sh --check   # fail if the committed lock is stale (CI)
#
# The compile runs inside the SAME uv the image pins (read out of the Dockerfile, so there is one
# source of truth), because a different uv can resolve differently — a lock produced by whatever
# happens to be on a contributor's laptop is not the lock the image would have built.
#
# --universal is required: the image publishes linux/amd64 AND linux/arm64, so the lock has to carry
# environment markers rather than one architecture's resolution.

set -euo pipefail

cd "$(dirname "$0")/.."

DOCKERFILE="images/linux/Dockerfile"
IN="images/linux/requirements.in"
OUT="images/linux/requirements.txt"

read_arg() { # the pinned value of an ARG, so this script can never drift from the image
  local name="$1" value
  value="$(sed -n "s/^ARG ${name}=\(.*\)$/\1/p" "$DOCKERFILE" | head -1)"
  [ -n "$value" ] || { echo "::error::no ARG ${name} in ${DOCKERFILE}" >&2; exit 1; }
  printf '%s' "$value"
}

UV_VERSION="$(read_arg UV_VERSION)"
# Only major.minor reaches uv: --python-version takes the interpreter series, not the patch.
PYTHON_VERSION="$(read_arg WORKFLOW_PYTHON_VERSION | cut -d. -f1,2)"

echo "== compiling $IN with uv $UV_VERSION for python $PYTHON_VERSION (universal) =="

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# The -debian-slim variant, not the default scratch image: uv probes the local libc even for a
# universal resolve, and a scratch image has no /bin/sh for it to probe. Debian also matches the
# runner image's own base.
# -w /work so the input is named relatively: uv echoes the path it was given into the "via"
# annotations, and an absolute container path would bake this script's mount layout into the
# committed lock.
docker run --rm \
  -v "$PWD/images/linux:/work:ro" \
  -v "$tmp:/out" \
  -w /work \
  "ghcr.io/astral-sh/uv:${UV_VERSION}-debian-slim" \
  uv pip compile requirements.in \
  --universal \
  --python-version "$PYTHON_VERSION" \
  --no-header \
  --quiet \
  --output-file /out/requirements.txt

# Restore the explanatory header the --no-header build drops, so the file says how to regenerate it.
{
  echo "# Fully-pinned resolution of requirements.in — the closure the image actually installs."
  echo "# GENERATED by scripts/compile-python-deps.sh; do not hand-edit. To change a package, edit"
  echo "# requirements.in and re-run that script."
  cat "$tmp/requirements.txt"
} > "$tmp/final.txt"

if [ "${1:-}" = "--check" ]; then
  if ! diff -u "$OUT" "$tmp/final.txt"; then
    echo "::error::$OUT is stale — run scripts/compile-python-deps.sh and commit the result" >&2
    exit 1
  fi
  echo "$OUT is up to date."
else
  mv "$tmp/final.txt" "$OUT"
  echo "wrote $OUT"
fi
