#!/usr/bin/env bash
#
# Emit a deterministic manifest of what's installed in a runner image — the human-reviewable
# "environment lock". The baseline lives at images/<image>/ENVIRONMENT.lock and CI regenerates it on
# every PR; a drift fails the build, so any change to the build environment shows up as a reviewed
# diff in the PR itself (POLICY.md: "what changed in the environment is answerable from the PR
# alone"). This is the package-level companion to the full SPDX SBOM published on release.
#
# Usage: scripts/env-manifest.sh <image-tag>
#
# Determinism: sorted everywhere; runs offline (--network none) so nothing resolves at emit time.

set -euo pipefail

IMG="${1:?usage: env-manifest.sh <image-tag>}"

run() { docker run --rm --network none "$IMG" bash -lc "$1"; }

echo "# Boardwalk runner image environment lock"
echo "# Generated by scripts/env-manifest.sh — do not hand-edit; regenerate and commit on any change."
echo

echo "[tools]"
run '
  printf "node\t%s\n"    "$(node --version | sed "s/^v//")"
  printf "npm\t%s\n"     "$(npm --version)"
  printf "pnpm\t%s\n"    "$(pnpm --version)"
  printf "tsx\t%s\n"     "$(tsx --version | head -1 | awk "{print \$NF}" | sed "s/^v//")"
  printf "gh\t%s\n"      "$(gh --version | head -1 | awk "{print \$3}")"
  printf "python3\t%s\n" "$(python3 --version | awk "{print \$2}")"
  printf "git\t%s\n"     "$(git --version | awk "{print \$3}")"
' | sort
echo

echo "[npm-global]"
run 'npm ls -g --depth=0 --parseable 2>/dev/null | sed "s#.*/node_modules/##" | grep -vE "^(/|$)"' | sort
echo

echo "[apt-packages]"
# Escape the $ so the placeholders reach dpkg-query literally (the inner shell would otherwise
# expand ${Package}/${Version} as its own unset variables — to empty).
run 'dpkg-query -W -f "\${Package}\t\${Version}\n"' | sort
